### PR TITLE
Add finetuning settings, improve locales + fix URL's, include max_tokens for 3.5-turbo model

### PR DESCRIPTION
**Pull request by MarcRez33**

### CODE REVIEW

**Comment by MarcRez33** [comment]
The commit "@MarcRez33
[Add setting to enforce (prioritize) system role - first try](https://github.com/merefield/discourse-chatbot/pull/9/commits/75e12535f4263f4aa8fb61e34cf50c534cabee3b)" (and further) was not supposed to be in this PR. But now that it's working and I don't know how to remove it might as well leave it this way.

**Comment by merefield** [comment]
Thanks @MarcRez33.

* Ideally this should be two PRs, one for new response parameters and one other for system prompt order.
* Can you please share a reference in Open AI API docs that justify the system prompt change?
* Why is this only being applied to Messages and not the Posts.

Also can you please summarise the changes in the PR in bullet points in the OP?

**Comment by MarcRez33** [comment]
I have no clue what I'm actually doing, didn't mean to PR the second feature, but every commit after the PR appeared in this PR.

> Can you please share a reference in Open AI API docs that justify the system prompt change?

It was a personal feature, not in docs - as being discussed here: https://community.openai.com/t/the-system-role-how-it-influences-the-chat-behavior/87353/10

> Why is this only being applied to Messages and not the Posts?

It's being applied to Messages and Posts. I did posts first and did the commit for [Messages](https://github.com/merefield/discourse-chatbot/pull/9/commits/46133cfeb41fb93dc78ccf61cfc6dacb1aea129c) a bit later, after Posts was working as expected.

**Comment by MarcRez33** [comment]
Closing this as it will be split as soon as I figure out gits and branches.

**Pull request closed without merging**
